### ISSUE TITLE
Create contributing guide

### ISSUE THREAD

**Issue by adamazad** [cryptonative-ch/mesa-interface#31] opened 2021-01-27 17:23 UTC
As Mesa's squad plan to onboard a range of L1 to L3 developers, there should be a contributing guide/architecture. The guide will act as a cheat sheet for new developers to find their "way" in the codebase in the shortest time possible.

**Comment by martinkrung** [comment] 2021-02-03 12:50
duplicate of #46

**Closed by martinkrung** 2021-02-03 12:50 UTC
Labels: documentation
